addons:
  postgresql: "10.10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
  - AUTH_KEY = THI3_13_TH3_53C3T_K3Y

language: node_js

node_js: "stable"

services: 
- postgresql

before_script:
- psql -c "create database free_mentorsDB;" -U postgres

install: npm install

script: 
- npm run migrate
- npm run render-users
- npm run render-sessions
- npm run render-reviews
- npm test

after_script: 
- npm run migrate
- npm run coverage
