language: node_js

node_js: "stable"

services: 
- postgresql

before_script:
- psql -c "create database free_mentorsDB;" -U postgres

install: npm install

script: 
- npm run migrate
- npm run render-users
- npm run render-sessions
- npm run render-reviews
- npm test

after_script: 
- npm run migrate
- npm run coverage
